import { Playlist } from '../models/playlist';

export const PLAYLIST_FIXTURE: readonly Playlist[] = [
  {
    id: 'pl-rock-clasico',
    title: 'Rock Clásico',
    coverUrl: 'https://img/rock.jpg',
    trackCount: 42,
    owner: 'Camaleón Musical',
    migratable: true,
    platform: 'spotify',
  },
  {
    id: 'pl-gym-power',
    title: 'Gym Power',
    coverUrl: 'https://img/gym.jpg',
    trackCount: 35,
    owner: 'Camaleón Musical',
    migratable: true,
    platform: 'spotify',
  },
  {
    id: 'pl-chill-tarde',
    title: 'Chill de Tarde',
    coverUrl: 'https://img/chill.jpg',
    trackCount: 28,
    owner: 'Melómano Playlists',
    migratable: true,
    platform: 'spotify',
  },
  {
    id: 'pl-roadtrip-2026',
    title: 'Roadtrip 2026',
    coverUrl: 'https://img/roadtrip.jpg',
    trackCount: 51,
    owner: 'Melómano Playlists',
    migratable: true,
    platform: 'spotify',
  },
  {
    id: 'pl-fiesta-latina',
    title: 'Fiesta Latina',
    coverUrl: 'https://img/fiesta.jpg',
    trackCount: 47,
    owner: 'DJ Chispa',
    migratable: true,
    platform: 'spotify',
  },
  {
    id: 'pl-lofi-programar',
    title: 'Lo-fi para Programar',
    coverUrl: 'https://img/lofi.jpg',
    trackCount: 64,
    owner: 'Byte & Beat',
    migratable: true,
    platform: 'spotify',
  },
  {
    id: 'pl-nostalgia-2000',
    title: 'Nostalgia 2000',
    coverUrl: 'https://img/nostalgia.jpg',
    trackCount: 33,
    owner: 'DJ Chispa',
    migratable: true,
    platform: 'spotify',
  },
  {
    id: 'pl-duermete-bebe',
    title: 'Dúrmete, Bebé',
    coverUrl: 'https://img/bebe.jpg',
    trackCount: 19,
    owner: 'Camaleón Musical',
    migratable: true,
    platform: 'spotify',
  },
];
